site:
  title: StackSAGA Docs
  start_page: StackSaga::index.adoc
  url: https://docs.stacksaga.org
content:
  sources:
    - url: https://github.com/stacksaga/stacksaga-docs.git
      branches: feture/stacksaga-kafka-update
      start_path: docs
#    - url: https://github.com/mafei-dev/stacksaga-admin-docs.git
#      branches: main
#      start_path: docs
ui:
  bundle:
    url: ./theme
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - CNAME
    - path: CNAME
      contents: |
        docs.stacksaga.org
asciidoc:
  attributes:
    page-pagination: '@'
    source-highlighter: highlight.js